name: CI

on:
  release:
    types: [published]
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Push to GH Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_TOKEN }}
          repository: ghcr.io/mitchtalmadge/studybot
          tag_with_ref: true
